// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OllsWarehouse.Models;

namespace OllsWarehouse.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OllsWarehouse.Models.Films", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("movieCertificate")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("movieDescription")
                        .HasColumnType("text");

                    b.Property<string>("movieImage")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("moviePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("movieReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("movieTrailer")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("movieGenre")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("movieBackgroundImage")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("movieTitle")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("movieID");

                    b.ToTable("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
